### ISSUE TITLE
charts/horizon: helm install has failed pod startup

### ISSUE THREAD

**Issue by sreuland** [stellar/helm-charts#64]
### What version are you using?

`main`

### What did you do?
```
helm repo add stellar https://helm.stellar.org/charts && helm repo update stellar
helm install testhorizon stellar/horizon   --namespace sandbox   --set global.image.horizon.tag=2.26.1 --set global.network=testnet --devel

```

### What did you expect to see?
horizon service running on cluster

### What did you see instead?
statefulset startup failed due to pod/spec error:

```
kubectl get events -n sandbox
LAST SEEN   TYPE      REASON         OBJECT                          MESSAGE
69s         Warning   FailedCreate   statefulset/my-horizon-ingest   create Pod my-horizon-ingest-0 in StatefulSet my-horizon-ingest failed error: Pod "my-horizon-ingest-0" is invalid: spec.containers[0].envFrom[0].secretRef.name: Required value
```

looking at the statefulset created by helm on cluster, can see the `secretRef` issue, looks like it has invalid yaml, some empty braces:

```
....
 spec:
      containers:
      - args:
        - --apply-migrations
        envFrom:
        - secretRef: {}
        - configMapRef:
            name: my-horizon-ingest-env
        image: docker.io/stellar/stellar-horizon:2.26.1
        imagePullPolicy: Always
        name: horizon
....
```
